/* ============================================================
   awflow-import.ts — reading/validating/mapping .awflow.json
   files generated by the PG repo.

   Layers:
   - schema (a copy of the PG counterpart — kept in sync via
     AWFLOW_SCHEMA_VERSION; drift is an accepted risk);
   - parseAuFlowFile() validates at runtime (the input comes from
     outside this repo);
   - mapAuFlowToLocal() converts to the shape <FlowEditor> expects
     (Node<ScreenData|DecisionData>[] + Edge[] + meta + a proposed
     update). A pure function, no side effects.

   This module has NO UI. The (future) skills consume it:
     1. read the attached file
     2. parse + map
     3. orchestrate creating a new flow vs merging into an existing one
     4. resolve missing hrefs by asking the user
   ============================================================ */
import type { Edge, Node } from "@xyflow/react"
import { MarkerType } from "@xyflow/react"
import type { ScreenData, DecisionData } from "../_components/flow-editor"
import type { FlowUpdate } from "../_components/flow-updates"

/* MarkerType.ArrowClosed = "arrowclosed" at runtime. We keep a local const to
   avoid depending on runtime resolution (some server-side contexts import only
   the `type` enum and end up with no value). */
const ARROW_CLOSED: MarkerType = "arrowclosed" as MarkerType

/* ============================================================
   Schema (a copy of the contract in
   app/auis/prototype/_lib/awflow/schema.ts in the PG repo).
   Keep it in sync via schemaVersion.

   The string unions below (AuFlowCriterionType, AuFlowSection, …) are the
   EXTERNAL file format's values — data, not copy. Do not translate them.
   ============================================================ */

export const AWFLOW_SCHEMA_VERSION = 1 as const

export type AuFlowNodeKind = "screen" | "decision"
export type AuFlowSide = "t" | "b" | "l" | "r"
export type AuFlowSection = "studio" | "adm"
export type AuFlowChrome = "studio" | "bare"
export type AuFlowLayoutDirection = "TB" | "BT" | "LR" | "RL"

export type AuFlowNode = {
  id: string
  kind: AuFlowNodeKind
  title: string
  tag: string | null
  note: string | null
  question: string | null
  position: { x: number; y: number }
}

export type AuFlowEdge = {
  from: string
  to: string
  label: string | null
  branch: boolean
  fromSide: AuFlowSide | null
  toSide: AuFlowSide | null
}

export type AuFlowCriterionType =
  | "permissao"
  | "evento"
  | "validacao"
  | "billing"
  | "multi-tenant"
  | "audit"
  | "ux"
  | "regra"

export type AuFlowCriterion = { type: AuFlowCriterionType; text: string }

export type AuFlowScenario = {
  id: string
  title: string
  given: string
  when: string
  then: string
}

export type AuFlowScreen = {
  id: string
  name: string
  purpose: string
  scenarios: AuFlowScenario[]
  criteria: AuFlowCriterion[]
}

export type AuFlowNarrative = {
  persona: string
  context: string
  value: string
}

export type AuFlowMeta = {
  id: string
  label: string
  summary: string
  icon: string
  section: AuFlowSection
  chrome: AuFlowChrome
  layoutDirection: AuFlowLayoutDirection
  manualLayout: boolean
}

export type AuFlowFile = {
  schemaVersion: typeof AWFLOW_SCHEMA_VERSION
  exportedAt: string
  exportedFrom: { repo: string; route: string }
  flow: AuFlowMeta
  graph: { nodes: AuFlowNode[]; edges: AuFlowEdge[] }
  screens: AuFlowScreen[]
  narrative: AuFlowNarrative | null
}

/* ============================================================
   Parser — validates the minimum shape. Accepts .awflow.json coming
   from PG or from any source that honors the contract. It does not
   try to recover from errors; it returns an error for the skill to
   show the user.
   ============================================================ */

export type ParseResult =
  | { ok: true; file: AuFlowFile }
  | { ok: false; error: string }

export function parseAuFlowFile(input: unknown): ParseResult {
  const errs: string[] = []
  const v = input as Record<string, unknown> | null
  if (!v || typeof v !== "object") return { ok: false, error: "file is not a JSON object" }

  if (v.schemaVersion !== AWFLOW_SCHEMA_VERSION) {
    return {
      ok: false,
      error: `incompatible schemaVersion — expected ${AWFLOW_SCHEMA_VERSION}, got ${JSON.stringify(v.schemaVersion)}`,
    }
  }

  if (typeof v.exportedAt !== "string") errs.push("exportedAt must be an ISO-8601 string")
  if (!v.flow || typeof v.flow !== "object") errs.push("flow is missing")
  if (!v.graph || typeof v.graph !== "object") errs.push("graph is missing")
  else {
    const g = v.graph as { nodes?: unknown; edges?: unknown }
    if (!Array.isArray(g.nodes)) errs.push("graph.nodes must be an array")
    if (!Array.isArray(g.edges)) errs.push("graph.edges must be an array")
  }
  if (!Array.isArray(v.screens)) errs.push("screens must be an array")

  if (errs.length > 0) return { ok: false, error: errs.join("; ") }
  return { ok: true, file: v as unknown as AuFlowFile }
}

/* ============================================================
   Mapper — converts the file into the shape <FlowEditor> consumes.

   What it does NOT map automatically:
   - ScreenData.href: PG has no concept of href (real routes). We
     leave it empty; the consuming skill resolves it by asking.
   - toSide on the edges: our nodes only have a target on
     Position.Top. We keep it in data.originalSides for debugging,
     but we don't use it.
   ============================================================ */

type LocalScreenNode = Node<ScreenData>
type LocalDecisionNode = Node<DecisionData>
type LocalNode = LocalScreenNode | LocalDecisionNode

type EdgeData = {
  originalSides?: { fromSide: AuFlowSide | null; toSide: AuFlowSide | null }
}

export type MapResult = {
  meta: {
    id: string
    title: string
    description: string
    section: AuFlowSection
  }
  nodes: LocalNode[]
  edges: Edge<EdgeData>[]
  screens: AuFlowScreen[]
  narrative: AuFlowNarrative | null
  /** Suggested entry for updates[] when this is a merge. The skill tweaks the text. */
  proposedUpdate: FlowUpdate
  /** IDs of screens with no href set — the skill needs to fill them in. */
  screensMissingHref: string[]
}

export function mapAuFlowToLocal(file: AuFlowFile): MapResult {
  const screensById = new Map(file.screens.map((s) => [s.id, s]))
  const nodes: LocalNode[] = file.graph.nodes.map((n) => mapNode(n, screensById.get(n.id)))
  const edges: Edge<EdgeData>[] = file.graph.edges.map((e, i) => mapEdge(e, i, file.graph.nodes))

  const screensMissingHref = nodes
    .filter((n): n is LocalScreenNode => n.type === "screen")
    .filter((n) => !n.data.href)
    .map((n) => n.id)

  return {
    meta: {
      id: file.flow.id,
      title: file.flow.label,
      description: file.flow.summary,
      section: file.flow.section,
    },
    nodes,
    edges,
    screens: file.screens,
    narrative: file.narrative,
    proposedUpdate: buildProposedUpdate(file),
    screensMissingHref,
  }
}

function mapNode(n: AuFlowNode, screen: AuFlowScreen | undefined): LocalNode {
  if (n.kind === "decision") {
    return {
      id: n.id,
      type: "decision",
      position: n.position,
      data: {
        step: n.tag ?? "",
        title: n.title,
        question: n.question ?? "",
      },
    }
  }
  /* screen — the note can come from the node OR from screen.purpose (we prefer
     node.note when it is set, otherwise we use the purpose from the spec). */
  const note = n.note ?? screen?.purpose ?? ""
  return {
    id: n.id,
    type: "screen",
    position: n.position,
    data: {
      step: n.tag ?? "",
      title: n.title,
      href: "",
      note: note || undefined,
    },
  }
}

const HANDLE_BY_SIDE: Record<AuFlowSide, string> = {
  t: "top",
  b: "bottom",
  l: "left",
  r: "right",
}

function mapEdge(e: AuFlowEdge, i: number, nodes: AuFlowNode[]): Edge<EdgeData> {
  const sourceNode = nodes.find((n) => n.id === e.from)
  const sourceIsDecision = sourceNode?.kind === "decision"

  const sourceHandle =
    sourceIsDecision && e.fromSide && e.fromSide !== "t"
      ? HANDLE_BY_SIDE[e.fromSide]
      : undefined

  const baseStyle = e.branch
    ? { stroke: "var(--au-amber-500)", strokeWidth: 1.5 }
    : { stroke: "var(--border-strong)", strokeWidth: 1.5 }

  const markerColor = e.branch ? "var(--au-amber-500)" : undefined

  return {
    id: `e-${i}-${e.from}-${e.to}`,
    source: e.from,
    target: e.to,
    sourceHandle,
    label: e.label ?? undefined,
    type: "smoothstep",
    animated: false,
    markerEnd: {
      type: ARROW_CLOSED,
      width: 18,
      height: 18,
      ...(markerColor ? { color: markerColor } : {}),
    },
    style: baseStyle,
    data: { originalSides: { fromSide: e.fromSide, toSide: e.toSide } },
  }
}

function buildProposedUpdate(file: AuFlowFile): FlowUpdate {
  const today = todayISODate()
  return {
    date: today,
    summary: `Structure imported from ${file.exportedFrom.repo} (export from ${file.exportedAt.slice(0, 10)}).`,
    tags: ["flow-rework"],
  }
}

function todayISODate(): string {
  const d = new Date()
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, "0")
  const day = String(d.getDate()).padStart(2, "0")
  return `${y}-${m}-${day}`
}
